### ISSUE TITLE
Externalize Moodle configuration

### ISSUE THREAD

**Issue by michzimny** [up2university/docker-moodle#31]
... to have the config expressed in environmental variables and easily portable between environments.

It might be critical before the incoming big merge for production. Without this, it might be hard to properly move the necessary configuration from test to production.

**Comment by michzimny** [comment]
Found in Trello, probably relevant: 
Dockerfile for predictable installations. Site configuration customisations exported and reused via, e.g., https://moodle.org/plugins/block_admin_presets

**Comment by athird** [comment]
Coincidentally I've just been working on this with Nadav, I'm just about to send an email round asking for input from tool contributors for actual configurations. :-)

**Comment by michzimny** [comment]
Great! 👍

**Comment by athird** [comment]
Committed stuff to the auto_config branch - would you be able to test it using the env files from the private repository, please? They need to be in /envs/ mounted inside the moodle and mysql containers, and configured by

docker-compose exec moodle /configure.sh
docker-compose exec mysql /configure.sh

(in that order)

**Comment by michzimny** [comment]
I have locally tested the configuration of "test" instance.

> docker-compose exec moodle /configure.sh

For a fresh instance it ends up with some errors:
https://pastebin.com/n6ncAMwr

>  docker-compose exec mysql /configure.sh

Produced no output.

SSO seems not to be set up, probably because of the aforementioned errors.

Can these scripts be run over and over again? I would see them be added to images' entrypoints to be run on every start of a container. We probably want instances to automatically get reconfigured if we push some changes to .env files.

How to log in as admin to such instance? Is admin password set somewhere in .env files?

**Comment by michzimny** [comment]
I pushed some minor changes to your branch: https://github.com/up2university/docker-moodle/commit/703d1d3dcd6799894be056bb28abf136c0803842

I think we should also:
* file up envs/ with some template config files
* move current .env to envs/common.env or similarily

**Comment by athird** [comment]
Those errors are weird, I can't think why it would be trying to insert session data. I'll try to reproduce them here. And look into why SSL doesn't work.

If MySQL configure.sh script works, there shouldn't be any output from it.

As it is, they can't quite be run again and again, because they'll create duplicate entries for, e.g., the various repositories, but I'm tidying that up right now. I initially had them running in the entry points and took it out to give a little more control over when reconfiguration happens. It's fine to put them back in there (or trigger a rerun of configure.sh when there's an .env change? Probably easier to put them in the entrypoints, although something will still need to trigger the restart of the relevant containers).

What do you mean by "file up envs/ with some template config files"? 

I agree about moving .env into envs/common.env.

**Comment by michzimny** [comment]
Sorry, I meant to fill up the 'envs' directory in the repo with some templates.

I just reproduced on a fresh instance with the same errors.

**Comment by athird** [comment]
Ah, OK, thanks. Yes, I'll add some templates.

Try the latest commit, it should fix the setup error with a fresh instance. 

SAML2 still isn't working, but I think I know what's wrong - we need to force it to download the IdP metadata (easy), and extract the arguments that Moodle passes to openssl to generate certificates for it (not quite as easy but not hard). There'll still need to be a manual step, because the SP needs to be whitelisted by the SSO, but it should bring it down.

**Comment by michzimny** [comment]
> Try the latest commit, it should fix the setup error with a fresh instance.

It seems I get the same errors with the latest commit and with a fresh instance.

**Comment by michzimny** [comment]
Ah, I haven't updated my Docker images correctly after last commits. Testing again...

**Comment by athird** [comment]
OK, hope it works this time. 

Most recent commit should now have SSO configured properly (pending whitelisting), though not yet set as default displayed login method. (That's a one-line change, though.)

**Comment by michzimny** [comment]
I get very similiar errors with the most recent commits:
https://pastebin.com/fXEEchj6

**Comment by athird** [comment]
How about now? Sorry...

**Comment by michzimny** [comment]
After the recent changes (the log has changed a little bit):
https://pastebin.com/ECj3CVCZ

**Comment by athird** [comment]
Are you sure your images were updated again? I can't reproduce it this time. If it helps, I've just pushed some additions to the env files on the other repository, but the main thing that fixed this error should be in the latest in this branch.

**Comment by michzimny** [comment]
I've just used the recent updates from the env repo (config files of "test" instance). I've deleted all Docker images and then downloaded the recent for auto_config branch. I've run a fresh instance and get:
https://pastebin.com/TtxfsQUv

**Comment by athird** [comment]
OK, I was able to reproduce it, could you try the latest commit, please?

**Comment by michzimny** [comment]
The scripts passed this time!

In the env repo you have some 'localhost' in the files of 'test' instance.

**Comment by athird** [comment]
Excellent! Ah, thanks. I've just fixed that.

**Comment by michzimny** [comment]
How about running the configure scripts multiple times? Can we call them from Docker's entrypoints?

**Comment by athird** [comment]
OK, so it's fine to run them multiple times, but running them from Docker entry points seems sometimes to go wrong, due to what seem to be timing issues between the mysql and moodle images (moodle trying to run things when the db isn't ready). Would it be too much of a pain just to have the deploy script call 'docker exec ...' for both containers?

**Comment by michzimny** [comment]
It's ok to call configure.sh from a deploy script.

PR for this issue: #40.

**Comment by michzimny** [comment]
#41
